/**
 * FrequencySeaEngine — organic, reactive Web Audio synthesis for the Frequency Sea.
  *
   * Layers:
    *  1. Tidal Swell  — pink-ish noise through a breathing bandpass filter (waves)
     *  2. Deep Swell   — low-frequency oscillator modulated by a very slow LFO (pressure)
      *  3. Ionosphere Crackle — high-pass micro-static that crackles at wave peaks (texture)
       *
        * The slider Q-coupling lets the calling component wire slider proximity so that
         * the ocean drops volume when a user nears one of the hidden "stations".
          */

          type SeaEngineOptions = {
            /** 0-1 master volume for the whole sea layer (default 1) */
              masterVolume?: number
              }

              class FrequencySeaEngine {
                private ctx: AudioContext | null = null
                  private masterGain: GainNode | null = null
                    private tidalFilter: BiquadFilterNode | null = null
                      private tidalGain: GainNode | null = null
                        private deepOsc: OscillatorNode | null = null
                          private deepLfoOsc: OscillatorNode | null = null
                            private crackleGain: GainNode | null = null
                              private lfoIntervalId: ReturnType<typeof setInterval> | null = null
                                isRunning = false

                                  start(options: SeaEngineOptions = {}) {
                                      if (this.isRunning) return
                                          const AudioContextClass =
                                                (window as unknown as { webkitAudioContext?: typeof AudioContext })
                                                        .webkitAudioContext ?? (window as unknown as { AudioContext?: typeof AudioContext }).AudioContext
                                                            if (!AudioContextClass) return

                                                                this.ctx = new AudioContextClass()
                                                                    const ctx = this.ctx
                                                                        this.isRunning = true

                                                                            // ─── Master gain ──────────────────────────────────────────────────────────
                                                                                this.masterGain = ctx.createGain()
                                                                                    this.masterGain.gain.value = options.masterVolume ?? 1
                                                                                        this.masterGain.connect(ctx.destination)

                                                                                            // ─── 1. TIDAL SWELL — pink-noise source + breathing bandpass ─────────────
                                                                                                const bufferSize = 2 * ctx.sampleRate
                                                                                                    const noiseBuffer = ctx.createBuffer(1, bufferSize, ctx.sampleRate)
                                                                                                        const noiseData = noiseBuffer.getChannelData(0)
                                                                                                            // Pink-ish noise: integrate white noise with a simple first-order filter
                                                                                                                let b0 = 0, b1 = 0, b2 = 0, b3 = 0, b4 = 0, b5 = 0, b6 = 0
                                                                                                                    for (let i = 0; i < bufferSize; i++) {
                                                                                                                          const white = Math.random() * 2 - 1
                                                                                                                                b0 = 0.99886 * b0 + white * 0.0555179
                                                                                                                                      b1 = 0.99332 * b1 + white * 0.0750759
                                                                                                                                            b2 = 0.96900 * b2 + white * 0.1538520
                                                                                                                                                  b3 = 0.86650 * b3 + white * 0.3104856
                                                                                                                                                        b4 = 0.55000 * b4 + white * 0.5329522
                                                                                                                                                              b5 = -0.7616 * b5 - white * 0.0168980
                                                                                                                                                                    b6 = white * 0.115926
                                                                                                                                                                          noiseData[i] = (b0 + b1 + b2 + b3 + b4 + b5 + b6 + white * 0.5362) * 0.11
                                                                                                                                                                              }
                                                                                                                                                                              
                                                                                                                                                                                  const noiseSrc = ctx.createBufferSource()
                                                                                                                                                                                      noiseSrc.buffer = noiseBuffer
                                                                                                                                                                                          noiseSrc.loop = true
                                                                                                                                                                                          
                                                                                                                                                                                              this.tidalFilter = ctx.createBiquadFilter()
                                                                                                                                                                                                  this.tidalFilter.type = 'bandpass'
                                                                                                                                                                                                      this.tidalFilter.frequency.value = 300
                                                                                                                                                                                                          this.tidalFilter.Q.value = 2.0
                                                                                                                                                                                                          
                                                                                                                                                                                                              this.tidalGain = ctx.createGain()
                                                                                                                                                                                                                  this.tidalGain.gain.value = 0.55
                                                                                                                                                                                                                  
                                                                                                                                                                                                                      noiseSrc.connect(this.tidalFilter)
                                                                                                                                                                                                                          this.tidalFilter.connect(this.tidalGain)
                                                                                                                                                                                                                              this.tidalGain.connect(this.masterGain)
                                                                                                                                                                                                                                  noiseSrc.start()
                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                      // Breathing LFO: cycle filter cutoff between ~150 Hz and ~450 Hz every ~5 s
                                                                                                                                                                                                                                          this.lfoIntervalId = setInterval(() => {
                                                                                                                                                                                                                                                if (!ctx || !this.tidalFilter) return
                                                                                                                                                                                                                                                      const now = ctx.currentTime
                                                                                                                                                                                                                                                            const waveCycle = 300 + Math.sin(now * 1.26) * 150
                                                                                                                                                                                                                                                                  this.tidalFilter.frequency.setTargetAtTime(waveCycle, now, 0.4)
                                                                                                                                                                                                                                                                        // Also breathe the gain slightly for a living feel
                                                                                                                                                                                                                                                                              if (this.tidalGain) {
                                                                                                                                                                                                                                                                                      const gainBreath = 0.48 + Math.sin(now * 0.62) * 0.12
                                                                                                                                                                                                                                                                                              this.tidalGain.gain.setTargetAtTime(gainBreath, now, 0.6)
                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                        }, 80)
                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                            // ─── 2. DEEP SWELL — low-freq oscillator + slow LFO ──────────────────────
                                                                                                                                                                                                                                                                                                                this.deepOsc = ctx.createOscillator()
                                                                                                                                                                                                                                                                                                                    this.deepOsc.type = 'sine'
                                                                                                                                                                                                                                                                                                                        this.deepOsc.frequency.value = 38 // Hz — sub-bass pressure
                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                            this.deepLfoOsc = ctx.createOscillator()
                                                                                                                                                                                                                                                                                                                                this.deepLfoOsc.type = 'sine'
                                                                                                                                                                                                                                                                                                                                    this.deepLfoOsc.frequency.value = 0.05 // 0.05 Hz → ~20-second tide cycle
                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                        const lfoGain = ctx.createGain()
                                                                                                                                                                                                                                                                                                                                            lfoGain.gain.value = 6 // modulate the deep osc ±6 Hz
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                const deepGain = ctx.createGain()
                                                                                                                                                                                                                                                                                                                                                    deepGain.gain.value = 0.07
                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                        this.deepLfoOsc.connect(lfoGain)
                                                                                                                                                                                                                                                                                                                                                            lfoGain.connect(this.deepOsc.frequency)
                                                                                                                                                                                                                                                                                                                                                                this.deepOsc.connect(deepGain)
                                                                                                                                                                                                                                                                                                                                                                    deepGain.connect(this.masterGain)
                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                        this.deepOsc.start()
                                                                                                                                                                                                                                                                                                                                                                            this.deepLfoOsc.start()
                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                // ─── 3. IONOSPHERE CRACKLE — high-pass micro-static ─────────────────────
                                                                                                                                                                                                                                                                                                                                                                                    const crackleBufferSize = ctx.sampleRate
                                                                                                                                                                                                                                                                                                                                                                                        const crackleBuffer = ctx.createBuffer(1, crackleBufferSize, ctx.sampleRate)
                                                                                                                                                                                                                                                                                                                                                                                            const crackleData = crackleBuffer.getChannelData(0)
                                                                                                                                                                                                                                                                                                                                                                                                for (let i = 0; i < crackleBufferSize; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                      // Sparse impulses: ~2 % probability per sample creates crackle texture
                                                                                                                                                                                                                                                                                                                                                                                                            crackleData[i] = Math.random() < 0.02 ? (Math.random() * 2 - 1) : 0
                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                    const crackleSrc = ctx.createBufferSource()
                                                                                                                                                                                                                                                                                                                                                                                                                        crackleSrc.buffer = crackleBuffer
                                                                                                                                                                                                                                                                                                                                                                                                                            crackleSrc.loop = true
                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                const crackleHPF = ctx.createBiquadFilter()
                                                                                                                                                                                                                                                                                                                                                                                                                                    crackleHPF.type = 'highpass'
                                                                                                                                                                                                                                                                                                                                                                                                                                        crackleHPF.frequency.value = 3200
                                                                                                                                                                                                                                                                                                                                                                                                                                            crackleHPF.Q.value = 0.7
                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                this.crackleGain = ctx.createGain()
                                                                                                                                                                                                                                                                                                                                                                                                                                                    this.crackleGain.gain.value = 0.04
                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                        crackleSrc.connect(crackleHPF)
                                                                                                                                                                                                                                                                                                                                                                                                                                                            crackleHPF.connect(this.crackleGain)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                this.crackleGain.connect(this.masterGain)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    crackleSrc.start()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        stop() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!this.isRunning) return
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (this.lfoIntervalId !== null) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      clearInterval(this.lfoIntervalId)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            this.lfoIntervalId = null
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    try { this.ctx?.close() } catch { /* already closed */ }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        this.ctx = null
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            this.masterGain = null
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                this.tidalFilter = null
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    this.tidalGain = null
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        this.deepOsc = null
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            this.deepLfoOsc = null
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                this.crackleGain = null
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    this.isRunning = false
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * Set the master volume.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              * Called by the slider-proximity logic: drop to ~0.5 when near a station,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * restore to 1.0 when away.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      setMasterVolume(v: number, rampSeconds = 1.2) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (!this.masterGain || !this.ctx) return
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              this.masterGain.gain.setTargetAtTime(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Math.max(0, Math.min(1, v)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          this.ctx.currentTime,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                rampSeconds / 3,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * Widen or sharpen the tidal bandpass Q.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              * At a station Q drops → ocean becomes diffuse; away Q rises → tighter wave.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   setTidalQ(q: number) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if (!this.tidalFilter) return
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           this.tidalFilter.Q.value = Math.max(0.5, Math.min(12, q))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             /** Singleton instance — import and call .start() / .stop() from FrequenciesScreen */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             export const frequencySeaEngine = new FrequencySeaEngine()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
